Profiles:
  OrdererGenesis:
    Orderer:
      OrdererType: solo
      Addresses:
        - orderer.zhang.com:7050
      BatchTimeout: 2s

      # Batch Size: Controls the number of messages batched into a block
      BatchSize:

          # Max Message Count: The maximum number of messages to permit in a batch
          MaxMessageCount: 10

          # Absolute Max Bytes: The absolute maximum number of bytes allowed for
          # the serialized messages in a batch.
          AbsoluteMaxBytes: 99 MB

          # Preferred Max Bytes: The preferred maximum number of bytes allowed for
          # the serialized messages in a batch. A message larger than the preferred
          # max bytes will result in a batch larger than preferred max bytes.
          PreferredMaxBytes: 512 KB

      Kafka:
          # Brokers: A list of Kafka brokers to which the orderer connects
          # NOTE: Use IP:port notation
          Brokers:
              - 127.0.0.1:9092

      # Organizations is the list of orgs which are defined as participants on
      # the orderer side of the network
      Organizations:
        - Name: OrdererOrg
          ID: OrdererMSP
          MSPDir: crypto-config/ordererOrganizations/zhang.com/msp
    Consortiums:
      BMFNConsortiums:
        Organizations:
          - *Org0
          - *Org1
  BMFNChannel:
    Consortium: BMFNConsortiums
    Application:
      Organizations:
        - *Org0
        - *Org1

Organizations:
  - &Org0
      Name: Org0MSP
      ID: Org0MSP
      MSPDir: crypto-config/peerOrganizations/org0.zhang.com/msp
      AnchorPeers:
        - Host: peer0.org0.zhang.com
          Port: 7051

  - &Org1
      Name: Org1MSP
      ID: Org1MSP
      MSPDir: crypto-config/peerOrganizations/org1.zhang.com/msp
      AnchorPeers:
        - Host: peer0.org1.zhang.com
          Port: 7051